const app = document.querySelector('#app');
const notice = document.querySelector('#notice');
const titles = {overview:'Financial Control Overview',reconciliation:'Reconciliation',controls:'Control Violations',anomalies:'Anomaly Detection',investigations:'Investigations',reports:'Risk & Audit Reports'};
let apiBase = localStorage.getItem('razcontrol-api') || 'http://localhost:8000';
document.querySelector('#api-url').value = apiBase;
const esc = value => String(value ?? '').replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const json = value => esc(JSON.stringify(value ?? {}, null, 2));
function showNotice(message, kind='error'){notice.innerHTML = `<div class="notice ${kind}">${esc(message)}</div>`;}
function clearNotice(){notice.innerHTML='';}
async function api(path, options={}){const response=await fetch(`${apiBase}${path}`,{headers:{'Content-Type':'application/json',...(options.headers||{})},...options});if(!response.ok){let text;try{text=(await response.json()).detail}catch{text=response.statusText}throw new Error(`${response.status}: ${text}`)}return response.json();}
function status(value){return `<span class="badge ${esc(value)}">${esc(value)}</span>`}
function metrics(items){return `<div class="grid metrics">${items.map(([label,value,cls=''])=>`<article class="card metric"><div class="value ${cls}">${esc(value)}</div><div class="label">${esc(label)}</div></article>`).join('')}</div>`}
function table(headers, rows){return `<div class="table-wrap"><table><thead><tr>${headers.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows||'<tr><td colspan="99">No records found.</td></tr>'}</tbody></table></div>`}
async function overview(){const report=await api('/reports/summary');const recon=report.reconciliation.by_status;return metrics([['Total transactions',report.total_transactions],['Matched',recon.MATCHED||0,'risk LOW'],['Review required',recon.REVIEW||0,'risk MEDIUM'],['Unmatched',recon.UNMATCHED||0,'risk HIGH'],['Control violations',report.control_violations.total],['Anomalies',report.anomalies.total],['High-risk findings',report.high_risk_findings,'risk HIGH'],['Open investigations',report.investigations.open]])+`<div class="grid summary-grid"><article class="card"><h2 class="section-title">Overall risk</h2><div class="value risk ${report.overall_risk}">${report.overall_risk}</div><p class="detail">Calculated from persisted HIGH and MEDIUM findings.</p></article><article class="card"><h2 class="section-title">Investigation workflow</h2><p><b>${report.investigations.open}</b> open · <b>${report.investigations.resolved}</b> resolved</p><p class="detail">Reports only aggregate verified backend results.</p></article></div>`;}
async function reconciliation(){const data=await api('/reconciliation/results');return `<p class="detail">Showing the latest ${data.results.length} of ${data.total} persisted reconciliation results.</p>`+table(['Bank transaction','Status','Confidence','Matched GL','Reason'],data.results.map(x=>`<tr><td>${esc(x.bank_transaction_id)}</td><td>${status(x.status)}</td><td>${esc(x.confidence)}%</td><td>${esc(x.transaction_id||'—')}</td><td>${esc(x.reason)}</td></tr>`).join(''));}
async function controls(){const data=await api('/guard/findings');return `<p class="detail">Showing ${data.findings.length} of ${data.total} persisted control violations.</p>`+findingsView(data.findings,'Controls');}
async function anomalies(){const data=await api('/detect/anomalies');return table(['Anomaly','Transaction','Score','Severity','Method','Reason'],data.anomalies.map(x=>`<tr><td>${esc(x.anomaly_id)}</td><td>${esc(x.transaction_id)}</td><td>${esc(x.risk_score)}</td><td>${status(x.severity)}</td><td>${esc(x.detection_method)}</td><td>${esc(x.explanation)}</td></tr>`).join(''));}
async function investigations(){const data=await api('/investigations');return table(['Investigation','Target','Status','Risk assessment','Recommended action'],data.investigations.map(x=>`<tr><td>${esc(x.investigation_id)}</td><td>${esc(x.target_type)}: ${esc(x.target_id)}</td><td>${status(x.status)}</td><td>${esc(x.risk_assessment)}</td><td>${esc(x.recommended_next_action)}</td></tr>`).join(''));}
function findingsView(findings, label){window.currentFindings=findings;return `<div class="filters"><input id="finding-filter" placeholder="Filter ${label.toLowerCase()}" /></div><div id="finding-list" class="card">${renderFindings(findings)}</div>`;}
function renderFindings(items){window.currentFindings=items;window.renderFindings=renderFindings;return items.length?items.map(x=>`<article class="finding"><div><b>${esc(x.finding_id||x.control_id)}</b><br>${status(x.severity)}</div><div><b>${esc(x.control_id||x.anomaly_type||'Finding')}</b><p>${esc(x.explanation||x.description||'')}</p><div class="evidence">${json(x.evidence)}</div></div><div>${status(x.status)}<p class="detail">${esc(x.transaction_id||x.record_id||'')}</p></div></article>`).join(''):`<div class="empty">No ${label.toLowerCase()} found.</div>`;}
async function reports(){const data=await api('/reports/overall');return `<div class="filters"><span class="detail">Showing ${data.findings.length} of ${data.total_findings} findings.</span><a class="export" href="${esc(apiBase)}/reports/export/csv">Download CSV export</a></div>${metrics([['Overall risk',data.summary.overall_risk,`risk ${data.summary.overall_risk}`],['High-risk findings',data.summary.high_risk_findings],['Resolved findings',data.summary.resolved_findings]])}${findingsView(data.findings,'report findings')}`;}
async function render(){const page=(location.hash||'#overview').slice(1);const key=titles[page]?page:'overview';document.querySelector('#page-title').textContent=titles[key];document.querySelector('#page-label').textContent=key.toUpperCase();document.querySelectorAll('nav a').forEach(a=>a.classList.toggle('active',a.getAttribute('href')===`#${key}`));clearNotice();app.innerHTML='<div class="loading">Loading verified financial data…</div>';try{app.innerHTML=await ({overview,reconciliation,controls,anomalies,investigations,reports}[key])();const filter=document.querySelector('#finding-filter');if(filter)filter.oninput=e=>document.querySelector('#finding-list').innerHTML=renderFindings(window.currentFindings.filter(x=>JSON.stringify(x).toLowerCase().includes(e.target.value.toLowerCase())));}catch(error){app.innerHTML=`<div class="empty">Unable to load this view.</div>`;showNotice(`Backend integration error: ${error.message}`);}}
document.querySelector('#save-api').onclick=()=>{apiBase=document.querySelector('#api-url').value.replace(/\/$/,'');localStorage.setItem('razcontrol-api',apiBase);showNotice('Backend endpoint saved.','success');render();};
document.querySelector('#pipeline-run').onclick=async()=>{const button=document.querySelector('#pipeline-run');button.disabled=true;button.textContent='Running…';try{const result=await api('/pipeline/run',{method:'POST'});showNotice(`Pipeline ${result.status.replace('_',' ').toLowerCase()}.`,'success');}catch(error){showNotice(`Pipeline failed: ${error.message}`)}finally{button.disabled=false;button.textContent='Run control pipeline';render();}};
window.addEventListener('hashchange',render);render();
